### ISSUE TITLE
"starting"?

### ISSUE THREAD

**Issue by DavidHolmes0** [jyuan5/CheesyBusiness#2]
Was our discussion during class clear on the use of "starting" in "it is possible to leave the starting position and reach treasure"?

I originally inferred that "starting" meant "the explorer's location" at the beginning of a particular execution of the recursive procedure". I think that meaning will serve you well, so I did not object to the phrasing. But then during the discussion, it seemed that you might have meant "The start of the root call for this problem". 

If this is accurate, it marks a rare occasion when I should have been *more* picky. The less-helpful interpretation did occur to me on the first reading, but I figured that no one wanted even more complaints from me.

**Comment by jyuan5** [comment]
You were correct in your inference. When we say "starting position," we are referring to the explorer's current location, including the "start of the root call for this problem" _and_ the positions the explorer occupies as it solves the maze. The starting position changes with every recursion. Thank you for seeking clarification.
