### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by LeoGreenleaf** [jyuan5/CheesyBusiness#4]
This was extremely well written and easy to comprehend. 
The only thing I found myself questioning is why the first three steps in the recursive abstractions of the pseudocode are in the order they are in. In my mind (which may be wrong), determining the next possible cardinal direction with a stepping stone (step 1) requires first moving one step in each of the cardinal directions (step 3 I think), which itself requires that you first drop a wall on the current position of your explorer (step 2), because theoretically, you would never be going back to the original current position once you branch off  into each cardinal direction with a stepping stone. 
Please correct me if this is wrong, because it may be my misconception of what we are meant to do to solve the maze.

**Comment by mbrydon19** [comment]
Thank you for pointing this out because we were trying to fix this in class and weren't sure if it was clear enough yet! I think you're right, that step 1 is essentially the same as step 3.
